### ISSUE TITLE
Detect ocam/cameras other than video0

### ISSUE THREAD

**Issue by fnoop** [fnoop/maverick#220]
If MFC or other v4l devices present, camera isn't guaranteed to be video0.  Still need to detect it both in puppet maverick_baremetal::peripherals classes and in maverick-visiond.

**Comment by siliconalchemy** [comment]
Default maverick-visiond.conf sets /dev/video0:
# Camera device, almost always /dev/video0
camera = /dev/video0

Perhaps this should autodetect.

**Comment by fnoop** [comment]
Default maverick-visiond.conf sets /dev/video0:
```
# Camera device, almost always /dev/video0
camera = /dev/video0
```

Perhaps this should autodetect.

**Comment by fnoop** [comment]
Added logic to maverick-visiond to scan through v4l devices and pick the camera device.  Changed default config to autodetect camera.
Also added logic to autodetect MFC encoder device.
