### ISSUE TITLE
Add rtsp server to visiond

### ISSUE THREAD

**Issue by fnoop** [fnoop/maverick#271]
Test rtsp implementation for easy video stream.
See if it can be broadcast through avahi or other mechanism.

**Comment by fnoop** [comment]
Some references:
https://github.com/GStreamer/gst-rtsp-server/tree/master/examples
https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-rtsp-server/html/GstRTSPServer.html
http://trac.gateworks.com/wiki/Yocto/gstreamer/streaming
https://github.com/Gateworks/gst-gateworks-apps/blob/master/src/gst-variable-rtsp-server.c

**Comment by fnoop** [comment]
Python refs:
https://github.com/paulmilliken/SimplePythonRtspExample/blob/master/AxisRtspSimple.py
http://stackoverflow.com/questions/36164830/gstreamer-rtsp-server-not-working-sdp-contains-no-streams

**Comment by fnoop** [comment]
http://stackoverflow.com/questions/34012197/data-transfer-through-rtsp-in-gstreamer

**Comment by Kiwa21** [comment]
https://github.com/Gateworks/gst-gateworks-apps/blob/master/src/gst-variable-rtsp-server.c

**Comment by fnoop** [comment]
https://www.metal3d.org/ticket/serveur-rstp-avec-gstreamer-et-python

**Comment by fnoop** [comment]
https://github.com/mpromonet/v4l2rtspserver

**Comment by fnoop** [comment]
http://gstreamer-devel.966125.n4.nabble.com/How-to-create-one-pipeline-for-both-audio-video-stream-and-only-video-stream-td4681575.html

**Comment by fnoop** [comment]
First run at rtsp server.  RTSP Server is working and supports multiple clients, but on the last client disconnecting visiond segfaults.  Suspect this is because it tries to tear down the pipeline, which it shouldn't do as it didn't create it.

**Comment by fnoop** [comment]
Segfaulting on all client shutdown isn't ideal, but the systemd service that controls visiond relaunches on failure, so practically speaking the user shouldn't notice - the rtsp service is immediately available again.
