### ISSUE TITLE
Add tracker, sub to sitl types

### ISSUE THREAD

**Issue by fnoop** [fnoop/maverick#402]
SITL currently supports copter, plane, rover.  Should also support tracker and sub.

**Comment by SamPes** [comment]
And boat? The simlulation dynamics are a bit different with a boat than with a rover.

**Comment by fnoop** [comment]
I don't think boat is a distinct vehicle type is it?  I can't see a firmware compile option or SITL vehicle type for it?

**Comment by fnoop** [comment]
Looks like boat support is within rover, but I can't even see a different frame type for boat.  I think from a system point of view this should be supported now with rover support.
