### ISSUE TITLE
Tensorflow issues on Odroid XU4

### ISSUE THREAD

**Issue by kiranshila** [fnoop/maverick#519]
maverick configure in dev env hangs on Tensorflow compile. How do I disable it?

**Comment by fnoop** [comment]
Good question, needs to be documented.  It probably doesn't hang, it's probably compiling it - on a raspberry it takes the best part of a day to compile!

**Comment by fnoop** [comment]
Doc added:
https://fnoop.github.io/maverick/#/modules/intelligence

**Comment by fnoop** [comment]
ps - if you ever have the patience to compile it, please do report back here any success/failure.  Would be great to have it supported on xu4.

**Comment by kiranshila** [comment]
Cool, I'll try tomorrow to compile it and have it run during work. I'm prepping an up to date Odroid image.
