### ISSUE TITLE
wifi-setup fails on passphrases with !

### ISSUE THREAD

**Issue by fnoop** [fnoop/maverick#535]
! gets interpreted by the shell and doesn't produce a correct psk.

**Comment by fnoop** [comment]
@lvale thanks for reporting :)

**Comment by lvale** [comment]
@fnoop no problem. Next time I'll report it correctly :)

**Comment by fnoop** [comment]
Spectacularly stupid fix, that now creates all encrypted psk with the passphrase $passphrase as this isn't escaped in the bash shell expansion in single quotes.

**Comment by fnoop** [comment]
Slightly less stupid fix in place now - echo and pipe passphrase to wpa_passphrase stdin instead of specifying directly, seems to work without expanding bangs.
