### ISSUE TITLE
previously working wifi no longer works after update to latest.

### ISSUE THREAD

**Issue by davidbuzz** [fnoop/maverick#612]
fault:
device does not reconnect to wifi that it was previously connected to just fine. 

steps to produce: 
download 'release' image for raspberry pi ( 1.1.1 ), install to SD and boot ( I used a rpi 3)
connect keyboard/screen and boot it.
run wifi-setup and answer Q's to get wifi connected to my local wifi here.
run 'maverick self-update ; maverick configure' as instructed to update to latest version/s.
after end of 'configure' reboot as instructed.
fault occurs right at that point. ( ie it drops off the wifi and stays there ).

**Comment by davidbuzz** [comment]
more details:    /etc/wpa_supplicant/wpa_supplicant.conf didn't have my local wifi creentials, it had a generic/default entry for the ssid, and no key ( just empty quotes ).     I edited the file to my local settings again, and then 'ifup wman0'  and/or a reboot seems to have got my wifi back again.   
This would have been impossible to fix headless.

**Comment by fnoop** [comment]
A lot of things have changed/been fixed since the 1.1.1 release, and from the 1.1.3 release that a self-update will currently take you to.  This should be re-tested with the upcoming 1.1.4 release, but is expected to work.

**Comment by fnoop** [comment]
Believe these issues are fixed in latest 1.1.4.  Leaving this open as a marker to make putting wpa_supplicant.conf on /boot FAT partition work as per normal raspberry headless setup.  ssh file isn't necessary as ssh server already enabled by default.

**Comment by fnoop** [comment]
```
lib/systemd/system/raspberrypi-net-mods.service:Description=Copy user wpa_supplicant.conf
lib/systemd/system/raspberrypi-net-mods.service:ConditionPathExists=/boot/wpa_supplicant.conf
lib/systemd/system/raspberrypi-net-mods.service:ExecStart=/bin/mv /boot/wpa_supplicant.conf /etc/wpa_supplicant/wpa_supplicant.conf
lib/systemd/system/raspberrypi-net-mods.service:ExecStartPost=/bin/chmod 600 /etc/wpa_supplicant/wpa_supplicant.conf
```
This is the mechanism that raspbian (desktop, stretch) uses to copy wpa_supplicant.conf.  Need to verify if present in raspbian lite.

**Comment by fnoop** [comment]
Yes, present in raspbian stretch lite a well:
```
more raspberrypi-net-mods.service 
[Unit]
Description=Copy user wpa_supplicant.conf
ConditionPathExists=/boot/wpa_supplicant.conf
Before=dhcpcd.service

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/bin/mv /boot/wpa_supplicant.conf /etc/wpa_supplicant/wpa_supplicant.conf
ExecStartPost=/bin/chmod 600 /etc/wpa_supplicant/wpa_supplicant.conf

[Install]
WantedBy=multi-user.target

```

**Comment by fnoop** [comment]
Oddly it's not present in latest maverick builds, even though they're based off raspbian stretch.

**Comment by fnoop** [comment]
```
var/lib/systemd/deb-systemd-helper-enabled/raspberrypi-net-mods.service.dsh-also:/etc/systemd/system/multi-user.target.wants/raspberrypi-net-mods.service
var/lib/dpkg/info/raspberrypi-net-mods.prerm:	deb-systemd-invoke stop raspberrypi-net-mods.service >/dev/null
var/lib/dpkg/info/raspberrypi-net-mods.postinst:deb-systemd-helper unmask raspberrypi-net-mods.service >/dev/null || true
var/lib/dpkg/info/raspberrypi-net-mods.postinst:if deb-systemd-helper --quiet was-enabled raspberrypi-net-mods.service; then
var/lib/dpkg/info/raspberrypi-net-mods.postinst:	deb-systemd-helper enable raspberrypi-net-mods.service >/dev/null || true
var/lib/dpkg/info/raspberrypi-net-mods.postinst:	deb-systemd-helper update-state raspberrypi-net-mods.service >/dev/null || true
var/lib/dpkg/info/raspberrypi-net-mods.postinst:	deb-systemd-invoke start raspberrypi-net-mods.service >/dev/null || true
var/lib/dpkg/info/raspberrypi-net-mods.md5sums:eaf207e6eb215df0bb0680d619ca815e  lib/systemd/system/raspberrypi-net-mods.service
var/lib/dpkg/info/raspberrypi-net-mods.list:/lib/systemd/system/raspberrypi-net-mods.service
var/lib/dpkg/info/raspberrypi-net-mods.postrm:		deb-systemd-helper mask raspberrypi-net-mods.service >/dev/null
var/lib/dpkg/info/raspberrypi-net-mods.postrm:		deb-systemd-helper purge raspberrypi-net-mods.service >/dev/null
var/lib/dpkg/info/raspberrypi-net-mods.postrm:		deb-systemd-helper unmask raspberrypi-net-mods.service >/dev/null
```
raspberrypi-net-mods package, ensure installed
