### ISSUE TITLE
Improve analysis log file type detection

### ISSUE THREAD

**Issue by fnoop** [fnoop/maverick#619]
Detect log type properly rather than file extension:
https://github.com/SamuelDudley/Hawkview/blob/master/app/lib/mavmemlog_np.py#L47

**Comment by fnoop** [comment]
Hawkview code depends on pymavlink.mavutil.mavlink_connection to open the file, which in turn depends on file extensions to determine file type anyway, so does not detect file type directly.

**Comment by fnoop** [comment]
Initial attempt at dataflash file format detection: try to read sample of file in as text and binary formats respectively, if >50% data is recognised set the file format.

**Comment by SamuelDudley** [comment]
@fnoop Yep your correct. Your implementation sounds good.
