### ISSUE TITLE
Beignet Compile Fails 

### ISSUE THREAD

**Issue by cglusky** [fnoop/maverick#701]
Up^2 self-update to master 1.1.5-dev

Log attached.

[maverick.dev.2017-12-02-20-49.log](https://github.com/fnoop/maverick/files/1524162/maverick.dev.2017-12-02-20-49.log)

**Comment by fnoop** [comment]
Could you please attach /srv/maverick/var/log/build/beignet.cmake.out?

**Comment by cglusky** [comment]
attached...

[beignet.cmake.out.txt](https://github.com/fnoop/maverick/files/1524340/beignet.cmake.out.txt)

[CMakeError.log](https://github.com/fnoop/maverick/files/1524343/CMakeError.log)

[CMakeOutput.log](https://github.com/fnoop/maverick/files/1524344/CMakeOutput.log)

**Comment by fnoop** [comment]
That's odd, I thought I had fixed that.  Can you see if you have the dependencies installed?
```
dpkg -l |grep clang
dpkg -l |grep llvm
```

**Comment by fnoop** [comment]
nvm I've replicated.

**Comment by fnoop** [comment]
Should be fixed now
